services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo

volumes:
  bundle_data:
  node_modules: