# アプリケーション名
service: omikuji

# Docker イメージの設定（Fly.io のレジストリ）
image: omikuji

# Fly.io のデプロイ先
servers:
  web:
    - omikuji.fly.dev

# SSL 設定（Fly.io はデフォルトで Let's Encrypt を使用）
proxy:
  ssl: true
  host: omikuji.fly.dev

# 環境変数
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    PORT: 4000
    RAILS_ENV: production

# Fly.io のボリューム設定（データ永続化）
volumes:
  - "fly_storage:/rails/storage"

# アセットのキャッシュ設定
asset_path: /rails/public/assets

# Docker ビルド設定
builder:
  arch: amd64

# SSH 設定（Fly.io のデフォルトユーザー）
ssh:
  user: fly

# コンテナレジストリの設定（Fly.io 用）
registry:
  server: registry.fly.io
  username: _json_key
  password: $FLY_ACCESS_TOKEN

# Fly.io のデータベースと Redis 設定
accessories:
  db:
    image: postgres:15
    host: omikuji-db.fly.dev
    env:
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
  redis:
    image: redis:7.0
    host: omikuji-redis.fly.dev
