service: omikuji
image: omikuji-vm/my-rails-app/omikuji

servers:
  web:
    - 35.185.215.236

ssh:
  user: kzkio

registry:
  server: us-west1-docker.pkg.dev
  username: _json_key
  password:
    - KAMAL_REGISTRY_JSON

env:
  secret:
    - RAILS_MASTER_KEY
    - KAMAL_REGISTRY_JSON
    - AWS_REGION
  clear:
    RAILS_ENV: production
    PORT: 4000
    DATABASE_URL: sqlite3:/app/storage/production.sqlite3

volumes:
  - "./storage:/app/storage"

builder:
  arch: amd64

