service: omikuji
image: omikuji-vm/my-rails-app/omikuji

servers:
  web:
    hosts:
      - 35.185.215.236
    options:
      health-cmd: curl -f http://localhost:80/up || exit 1
      health-start-period: 90s
      health-interval: 5s
      health-timeout: 5s
      health-retries: 5

accessories:
  queue:
    image: us-west1-docker.pkg.dev/omikuji-vm/my-rails-app/omikuji:latest
    cmd: bin/rails solid_queue:start
    roles:
      - web

ssh:
  user: kzkio

registry:
  server: us-west1-docker.pkg.dev
  username: _json_key
  password:
    - KAMAL_REGISTRY_JSON

proxy:
  app_port: 80
  ssl: true
  host: xn--t8jk1a7l204u.jp

env:
  secret:
    - RAILS_MASTER_KEY
    - KAMAL_REGISTRY_JSON
    - SECRET_KEY_BASE
    - R2_ACCESS_KEY_ID
    - R2_SECRET_ACCESS_KEY
    - R2_ENDPOINT
    - R2_BUCKET
    - AWS_REGION
  clear:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    RAILS_MAX_THREADS: 1
    WEB_CONCURRENCY: 0
    PORT: 80
    HOST: 0.0.0.0
    DATABASE_URL: sqlite3:/app/storage/production.sqlite3

volumes:
  - "./storage:/app/storage"

builder:
  arch: amd64