service: omikuji
image: omikuji-vm/my-rails-app/omikuji

servers:
  web:
    - 35.185.215.236

ssh:
  user: kzkio

registry:
  server: us-west1-docker.pkg.dev
  username: _json_key
  password:
    - KAMAL_REGISTRY_JSON

env:
  secret:
    - RAILS_MASTER_KEY
    - KAMAL_REGISTRY_JSON
    - R2_ACCESS_KEY_ID
    - R2_SECRET_ACCESS_KEY
    - R2_ENDPOINT
    - R2_BUCKET
    - AWS_REGION
  clear:
    RAILS_ENV: production
    RAILS_MAX_THREADS: 1
    WEB_CONCURRENCY: 0
    PORT: 4000
    HOST: 0.0.0.0
    DATABASE_URL: sqlite3:/app/storage/production.sqlite3

volumes:
  - "./storage:/app/storage"

builder:
  arch: amd64

